// app/src/app/admin/admin.component.ts
import { Component, Inject, PLATFORM_ID, CUSTOM_ELEMENTS_SCHEMA, OnInit } from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { SolanaService } from '../services/solana.service';
import { WalletService } from '../services/wallet.service';
import { FormsModule } from '@angular/forms';
import { PublicKey, SystemProgram, Keypair } from '@solana/web3.js';

interface Election {
  publicKey: string;
  title: string;
  status: 'active' | 'closed';
  endedAgo?: string;
  totalVotes: number;
  winner?: string;
  authority: string;
  isActive: boolean;
}

@Component({
  selector: 'app-admin',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './admin.component.html',
  styleUrls: ['./admin.component.css'],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AdminComponent implements OnInit {
  isBrowser = false;
  electionTitle = '';
  candidateName = '';
  loading = false;
  walletAddress: string | null = null;

  // Modal states
  showCreateModal = false;
  showCandidateModal = false;

  // Selected election for adding candidates
  selectedElectionPubkey: string | null = null;

  // Dashboard stats
  totalElections = 0;
  activeElections = 0;
  totalCandidates = 0;
  totalVoters = 0;

  // Elections list
  allElections: Election[] = [];
  recentElections: Election[] = [];
  activeElectionsList: Election[] = [];

  constructor(
    private solana: SolanaService,
    private wallet: WalletService,
    @Inject(PLATFORM_ID) platformId: Object
  ) {
    this.isBrowser = isPlatformBrowser(platformId);
  }

  async ngOnInit() {
    if (this.isBrowser) {
      // Give services time to initialize
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      await this.initializeComponent();
    }
  }

  private async initializeComponent() {
    try {
      // Step 1: Ensure wallet is connected
      const walletConnected = await this.ensureWalletConnected();
      if (!walletConnected) {
        console.log('⚠️ Wallet not connected, waiting for manual connection');
        return;
      }

      // Step 2: Wait a bit for wallet to fully settle
      await new Promise(resolve => setTimeout(resolve, 500));

      // Step 3: Try to load data
      await this.refreshData();
    } catch (error) {
      console.error('Error initializing component:', error);
    }
  }

  private async ensureWalletConnected(): Promise<boolean> {
    // Check if wallet is already connected
    if (this.wallet.isConnected()) {
      this.walletAddress = this.wallet.publicKey?.toString() || null;
      console.log('✅ Wallet already connected:', this.walletAddress);
      return true;
    }

    // Try auto-connect
    try {
      const address = await this.wallet.autoConnect();
      if (address) {
        this.walletAddress = address;
        console.log('✅ Auto-connected wallet:', address);
        return true;
      }
    } catch (e) {
      console.log('Auto-connect failed, manual connection required');
    }

    return false;
  }

  async connectWallet() {
    try {
      const address = await this.wallet.connect();
      if (address) {
        this.walletAddress = address;
        console.log('✅ Wallet connected:', address);
        
        // Wait for wallet to settle
        await new Promise(resolve => setTimeout(resolve, 500));
        
        // Refresh data
        await this.refreshData();
      }
    } catch (e) {
      console.error('Wallet connection failed:', e);
      this.showNotification('Failed to connect wallet', 'error');
    }
  }

  openCreateElectionModal() {
    if (!this.wallet.isConnected()) {
      this.showNotification('Please connect your wallet first', 'error');
      return;
    }
    this.showCreateModal = true;
  }

  closeCreateElectionModal() {
    this.showCreateModal = false;
    this.electionTitle = '';
  }

  openCandidateModal(electionPubkey?: string) {
    if (!this.wallet.isConnected()) {
      this.showNotification('Please connect your wallet first', 'error');
      return;
    }
    
    if (electionPubkey) {
      this.selectedElectionPubkey = electionPubkey;
    }
    this.showCandidateModal = true;
  }

  closeCandidateModal() {
    this.showCandidateModal = false;
    this.candidateName = '';
    this.selectedElectionPubkey = null;
  }

  async createElection() {
    if (!this.electionTitle || this.electionTitle.trim().length === 0) {
      this.showNotification('Please enter an election title', 'error');
      return;
    }

    if (this.electionTitle.length > 64) {
      this.showNotification('Title must be 64 characters or less', 'error');
      return;
    }

    if (!this.wallet.isConnected()) {
      this.showNotification('Please connect your wallet first', 'error');
      this.closeCreateElectionModal();
      return;
    }

    this.loading = true;

    try {
      // Get program with retry logic
      let program = await this.solana.getProgram();
      
      if (!program) {
        console.log('Program not available, refreshing wallet state...');
        await this.wallet.refreshWalletState();
        await new Promise(resolve => setTimeout(resolve, 500));
        program = await this.solana.getProgram();
      }
      
      if (!program) {
        this.showNotification(
          'Failed to initialize blockchain connection. Please refresh the page and try again.',
          'error'
        );
        this.loading = false;
        return;
      }

      if (!program.provider.publicKey) {
        this.showNotification('Wallet not found in program provider. Please reconnect.', 'error');
        this.loading = false;
        return;
      }

      const electionKeypair = Keypair.generate();

      const [adminPda] = PublicKey.findProgramAddressSync(
        [Buffer.from('admin'), program.provider.publicKey.toBuffer()],
        program.programId
      );

      console.log('Creating election...');
      console.log('Authority:', program.provider.publicKey.toString());
      console.log('Election Pubkey:', electionKeypair.publicKey.toString());
      console.log('Admin PDA:', adminPda.toString());

      const tx = await program.methods
        .createElection(this.electionTitle.trim())
        .accountsStrict({
          authority: program.provider.publicKey,
          adminAccount: adminPda,
          election: electionKeypair.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([electionKeypair])
        .rpc();

      console.log('✅ Transaction signature:', tx);
      console.log('✅ View on explorer: https://explorer.solana.com/tx/' + tx + '?cluster=devnet');

      this.showNotification(
        `✅ Election "${this.electionTitle}" created successfully!`,
        'success'
      );
      
      this.electionTitle = '';
      this.closeCreateElectionModal();
      
      setTimeout(() => this.refreshData(), 2000);

    } catch (e: any) {
      console.error('Error creating election:', e);
      
      let errorMsg = 'Failed to create election';
      
      if (e.message?.includes('TitleTooLong')) {
        errorMsg = 'Title is too long (max 64 characters)';
      } else if (e.message?.includes('Unauthorized') || e.message?.includes('0x7d6')) {
        errorMsg = 'You are not authorized. Please ensure:\n\n' +
                  '1. You are using the SUPER_ADMIN wallet, OR\n' +
                  '2. Your wallet has been added as an admin\n\n' +
                  'Current wallet: ' + (this.walletAddress || 'not connected');
      } else if (e.message?.includes('User rejected')) {
        errorMsg = 'Transaction was rejected';
      } else if (e.message?.includes('0x1')) {
        errorMsg = 'Insufficient funds. Please ensure you have enough SOL.';
      } else if (e.logs) {
        console.error('Transaction logs:', e.logs);
        errorMsg = 'Transaction failed. Check console for details.';
      } else if (e.message) {
        errorMsg = e.message;
      }
      
      this.showNotification(errorMsg, 'error');
    }

    this.loading = false;
  }

  async addCandidate() {
    if (!this.candidateName || this.candidateName.trim().length === 0) {
      this.showNotification('Please enter a candidate name', 'error');
      return;
    }

    if (this.candidateName.length > 32) {
      this.showNotification('Name must be 32 characters or less', 'error');
      return;
    }

    if (!this.selectedElectionPubkey) {
      this.showNotification('Please select an election first', 'error');
      return;
    }

    if (!this.wallet.isConnected()) {
      this.showNotification('Please connect your wallet first', 'error');
      this.closeCandidateModal();
      return;
    }

    this.loading = true;

    try {
      const program = await this.solana.getProgram();
      
      if (!program) {
        this.showNotification('Failed to initialize program. Please reconnect your wallet.', 'error');
        this.loading = false;
        return;
      }

      const candidateKeypair = Keypair.generate();
      const electionPubkey = new PublicKey(this.selectedElectionPubkey);

      console.log('Adding candidate...');
      console.log('Election:', electionPubkey.toString());
      console.log('Candidate Pubkey:', candidateKeypair.publicKey.toString());

      const tx = await program.methods
        .addCandidate(this.candidateName.trim())
        .accountsStrict({
          election: electionPubkey,
          candidate: candidateKeypair.publicKey,
          authority: program.provider.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([candidateKeypair])
        .rpc();

      console.log('✅ Transaction signature:', tx);

      this.showNotification(
        `✅ Candidate "${this.candidateName}" added successfully!`,
        'success'
      );
      
      this.candidateName = '';
      this.closeCandidateModal();
      
      setTimeout(() => this.refreshData(), 2000);

    } catch (e: any) {
      console.error('Error adding candidate:', e);
      
      let errorMsg = 'Failed to add candidate';
      if (e.message?.includes('NameTooLong')) {
        errorMsg = 'Name is too long (max 32 characters)';
      } else if (e.message?.includes('ElectionClosed')) {
        errorMsg = 'Cannot add candidate to a closed election';
      } else if (e.message?.includes('Unauthorized')) {
        errorMsg = 'You are not authorized to add candidates to this election';
      } else if (e.message) {
        errorMsg = e.message;
      }
      
      this.showNotification(errorMsg, 'error');
    }

    this.loading = false;
  }

  async closeElection(electionPubkey: string) {
    if (!confirm('Are you sure you want to close this election? This action cannot be undone.')) {
      return;
    }

    if (!this.wallet.isConnected()) {
      this.showNotification('Please connect your wallet first', 'error');
      return;
    }

    this.loading = true;

    try {
      const program = await this.solana.getProgram();
      
      if (!program) {
        this.showNotification('Failed to initialize program. Please reconnect your wallet.', 'error');
        this.loading = false;
        return;
      }

      const electionPublicKey = new PublicKey(electionPubkey);

      console.log('Closing election:', electionPublicKey.toString());

      const tx = await program.methods
        .closeElection()
        .accountsStrict({
          election: electionPublicKey,
          authority: program.provider.publicKey,
        })
        .rpc();

      console.log('✅ Transaction signature:', tx);

      this.showNotification('✅ Election closed successfully!', 'success');
      
      setTimeout(() => this.refreshData(), 2000);

    } catch (e: any) {
      console.error('Error closing election:', e);
      
      let errorMsg = 'Failed to close election';
      if (e.message?.includes('ElectionClosed')) {
        errorMsg = 'Election is already closed';
      } else if (e.message?.includes('Unauthorized')) {
        errorMsg = 'You are not authorized to close this election';
      } else if (e.message) {
        errorMsg = e.message;
      }
      
      this.showNotification(errorMsg, 'error');
    }

    this.loading = false;
  }

  async refreshData() {
    this.loading = true;

    try {
      const program = await this.solana.getProgram();
      if (!program) {
        console.log('Program not available, skipping data fetch');
        this.loading = false;
        return;
      }

      console.log('Fetching all elections and candidates...');

      const electionAccounts = await program.account.election.all();
      const candidateAccounts = await program.account.candidate.all();

      console.log(`Found ${electionAccounts.length} elections`);
      console.log(`Found ${candidateAccounts.length} candidates`);

      this.allElections = electionAccounts.map((acc: any) => ({
        publicKey: acc.publicKey.toString(),
        title: acc.account.title,
        status: acc.account.isActive ? 'active' : 'closed',
        totalVotes: acc.account.totalVotes.toNumber(),
        authority: acc.account.authority.toString(),
        isActive: acc.account.isActive,
        endedAgo: acc.account.isActive ? undefined : this.calculateTimeAgo(acc.account)
      }));

      this.totalElections = this.allElections.length;
      this.activeElections = this.allElections.filter(e => e.isActive).length;
      this.totalCandidates = candidateAccounts.length;

      this.recentElections = this.allElections
        .filter(e => e.status === 'closed')
        .slice(0, 5);

      this.activeElectionsList = this.allElections.filter(e => e.isActive);

      try {
        const voteRecords = await program.account.voteRecord.all();
        this.totalVoters = voteRecords.length;
      } catch (e) {
        console.log('Could not fetch vote records:', e);
        this.totalVoters = 0;
      }

      for (const election of this.recentElections) {
        const electionCandidates = candidateAccounts.filter(
          (c: any) => c.account.election.toString() === election.publicKey
        );

        if (electionCandidates.length > 0) {
          const winner = electionCandidates.reduce((prev: any, current: any) =>
            current.account.votes.toNumber() > prev.account.votes.toNumber() ? current : prev
          );
          election.winner = winner.account.name;
        } else {
          election.winner = 'No candidates';
        }
      }

      console.log('✅ Data refresh complete');

    } catch (e) {
      console.error('Error refreshing data:', e);
      // Don't show error notification on initial load
    }

    this.loading = false;
  }

  calculateTimeAgo(election: any): string {
    return 'recently';
  }

  showNotification(message: string, type: 'success' | 'error' | 'info') {
    if (type === 'success') {
      alert(`✅ ${message}`);
    } else if (type === 'error') {
      alert(`❌ ${message}`);
    } else {
      alert(`ℹ️ ${message}`);
    }
  }

  getActiveElections(): Election[] {
    return this.activeElectionsList;
  }
}
<div class="admin-dashboard">
  <!-- Sidebar -->
  <aside class="sidebar">
    <!-- Logo & Brand -->
    <div class="sidebar-brand">
      <div class="brand-icon">
        <iconify-icon icon="lucide:vote"></iconify-icon>
      </div>
      <span class="brand-name">SolVote Admin</span>
    </div>

    <!-- Navigation -->
    <nav class="sidebar-nav">
      <a href="#" class="nav-item active">
        <iconify-icon icon="lucide:layout-dashboard"></iconify-icon>
        <span>Dashboard</span>
      </a>
      <a href="#" class="nav-item">
        <iconify-icon icon="lucide:vote"></iconify-icon>
        <span>Elections</span>
        <span class="badge badge-success" *ngIf="activeElections > 0">{{ activeElections }} Active</span>
      </a>
      <a href="#" class="nav-item">
        <iconify-icon icon="lucide:bar-chart-3"></iconify-icon>
        <span>Results</span>
      </a>
      <a href="#" class="nav-item">
        <iconify-icon icon="lucide:users"></iconify-icon>
        <span>Voters</span>
      </a>
      <a href="#" class="nav-item">
        <iconify-icon icon="lucide:settings"></iconify-icon>
        <span>Settings</span>
      </a>
    </nav>

    <!-- Admin Wallet Info -->
    <div class="admin-wallet" *ngIf="walletAddress">
      <div class="wallet-avatar">
        <iconify-icon icon="lucide:user"></iconify-icon>
      </div>
      <div class="wallet-info">
        <span class="wallet-label">Admin Wallet</span>
        <span class="wallet-address">{{ walletAddress | slice:0:4 }}...{{ walletAddress | slice:-4 }}</span>
      </div>
    </div>
  </aside>

  <!-- Main Content -->
  <main class="main-content">
    <!-- Header -->
    <header class="content-header">
      <div class="header-left">
        <h1 class="page-title">Dashboard Overview</h1>
      </div>
      <div class="header-right">
        <!-- Show connect button if wallet not connected -->
        <button class="btn btn-primary" (click)="connectWallet()" *ngIf="!walletAddress">
          <iconify-icon icon="lucide:wallet"></iconify-icon>
          <span>Connect Wallet</span>
        </button>
        
        <!-- Show action buttons if wallet is connected -->
        <ng-container *ngIf="walletAddress">
          <button class="btn btn-refresh" (click)="refreshData()" [disabled]="loading">
            <iconify-icon icon="lucide:refresh-cw" [class.spinning]="loading"></iconify-icon>
            <span>Refresh Data</span>
          </button>
          <button class="btn btn-create" (click)="openCreateElectionModal()">
            <iconify-icon icon="lucide:plus"></iconify-icon>
            <span>Create Election</span>
          </button>
        </ng-container>
      </div>
    </header>

    <!-- Stats Grid -->
    <section class="stats-section">
      <div class="stat-card">
        <div class="stat-header">
          <span class="stat-label">Total Elections</span>
          <div class="stat-icon">
            <iconify-icon icon="lucide:file-text"></iconify-icon>
          </div>
        </div>
        <div class="stat-value">{{ totalElections }}</div>
        <div class="stat-footer">
          <span class="stat-change neutral">
            <iconify-icon icon="lucide:database"></iconify-icon>
            On-chain data
          </span>
        </div>
      </div>

      <div class="stat-card">
        <div class="stat-header">
          <span class="stat-label">Active Now</span>
          <div class="stat-icon active">
            <iconify-icon icon="lucide:activity"></iconify-icon>
          </div>
        </div>
        <div class="stat-value">{{ activeElections }}</div>
        <div class="stat-footer">
          <span class="stat-change success" *ngIf="activeElections > 0">
            <iconify-icon icon="lucide:zap"></iconify-icon>
            Live voting
          </span>
          <span class="stat-change neutral" *ngIf="activeElections === 0">
            No active elections
          </span>
        </div>
      </div>

      <div class="stat-card">
        <div class="stat-header">
          <span class="stat-label">Candidates</span>
          <div class="stat-icon">
            <iconify-icon icon="lucide:users"></iconify-icon>
          </div>
        </div>
        <div class="stat-value">{{ totalCandidates }}</div>
        <div class="stat-footer">
          <span class="stat-change success">
            <iconify-icon icon="lucide:check-circle"></iconify-icon>
            Registered
          </span>
        </div>
      </div>

      <div class="stat-card">
        <div class="stat-header">
          <span class="stat-label">Total Voters</span>
          <div class="stat-icon">
            <iconify-icon icon="lucide:users-2"></iconify-icon>
          </div>
        </div>
        <div class="stat-value">{{ totalVoters.toLocaleString() }}</div>
        <div class="stat-footer">
          <span class="stat-change success">
            <iconify-icon icon="lucide:vote"></iconify-icon>
            Votes cast
          </span>
        </div>
      </div>
    </section>

    <!-- Active Elections Section -->
    <section class="elections-section" *ngIf="activeElectionsList.length > 0">
      <div class="section-header">
        <h2 class="section-title">Active Elections</h2>
        <button class="btn-link" (click)="openCandidateModal()">Add Candidate</button>
      </div>

      <div class="elections-list">
        <div class="election-card" *ngFor="let election of activeElectionsList">
          <div class="election-main">
            <div class="election-info">
              <h3 class="election-title">{{ election.title }}</h3>
              <div class="election-meta">
                <span class="election-status active">{{ election.status }}</span>
                <span class="election-date">{{ election.publicKey | slice:0:8 }}...</span>
              </div>
            </div>
          </div>
          <div class="election-stats">
            <div class="election-stat">
              <span class="stat-label">Total Votes</span>
              <span class="stat-value">{{ election.totalVotes.toLocaleString() }}</span>
            </div>
            <button class="btn-icon" (click)="openCandidateModal(election.publicKey)" title="Add Candidate">
              <iconify-icon icon="lucide:user-plus"></iconify-icon>
            </button>
            <button class="btn-icon" (click)="closeElection(election.publicKey)" title="Close Election">
              <iconify-icon icon="lucide:lock"></iconify-icon>
            </button>
          </div>
        </div>
      </div>
    </section>

    <!-- Recently Closed Elections -->
    <section class="elections-section" *ngIf="recentElections.length > 0">
      <div class="section-header">
        <h2 class="section-title">Recently Closed Elections</h2>
        <button class="btn-link">View All</button>
      </div>

      <div class="elections-list">
        <div class="election-card" *ngFor="let election of recentElections">
          <div class="election-main">
            <div class="election-info">
              <h3 class="election-title">{{ election.title }}</h3>
              <div class="election-meta">
                <span class="election-status closed">{{ election.status }}</span>
                <span class="election-date">Ended {{ election.endedAgo }}</span>
              </div>
            </div>
          </div>
          <div class="election-stats">
            <div class="election-stat">
              <span class="stat-label">Total Votes</span>
              <span class="stat-value">{{ election.totalVotes.toLocaleString() }}</span>
            </div>
            <div class="election-stat">
              <span class="stat-label">Winner</span>
              <span class="stat-value">{{ election.winner }}</span>
            </div>
            <button class="btn-icon">
              <iconify-icon icon="lucide:chevron-right"></iconify-icon>
            </button>
          </div>
        </div>
      </div>
    </section>

    <!-- Empty State -->
    <section class="elections-section" *ngIf="!loading && totalElections === 0">
      <div class="empty-state">
        <div class="empty-icon">
          <iconify-icon icon="lucide:inbox"></iconify-icon>
        </div>
        <h3 class="empty-title">No Elections Yet</h3>
        <p class="empty-description">Create your first election to get started with SolVote.</p>
        <button class="btn btn-primary" (click)="openCreateElectionModal()">
          <iconify-icon icon="lucide:plus"></iconify-icon>
          <span>Create First Election</span>
        </button>
      </div>
    </section>
  </main>

  <!-- Create Election Modal -->
  <div class="modal-overlay" *ngIf="showCreateModal" (click)="closeCreateElectionModal()">
    <div class="modal" (click)="$event.stopPropagation()">
      <div class="modal-header">
        <h2 class="modal-title">Create New Election</h2>
        <button class="btn-close" (click)="closeCreateElectionModal()">
          <iconify-icon icon="lucide:x"></iconify-icon>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <label class="form-label">Election Title</label>
          <input 
            type="text" 
            class="form-input" 
            [(ngModel)]="electionTitle" 
            placeholder="e.g., Foundation Council Election 2024"
            maxlength="64"
          />
          <span class="form-hint">{{ electionTitle.length }}/64 characters</span>
        </div>
        <div class="form-group">
          <label class="form-label">Description (Optional)</label>
          <textarea 
            class="form-textarea" 
            rows="3" 
            placeholder="Brief description of the election..."
          ></textarea>
        </div>
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" (click)="closeCreateElectionModal()">Cancel</button>
        <button class="btn btn-primary" (click)="createElection()" [disabled]="loading || !electionTitle">
          <iconify-icon icon="lucide:plus" *ngIf="!loading"></iconify-icon>
          <iconify-icon icon="lucide:loader-2" class="spinning" *ngIf="loading"></iconify-icon>
          <span>{{ loading ? 'Creating...' : 'Create Election' }}</span>
        </button>
      </div>
    </div>
  </div>

  <!-- Add Candidate Modal -->
  <div class="modal-overlay" *ngIf="showCandidateModal" (click)="closeCandidateModal()">
    <div class="modal" (click)="$event.stopPropagation()">
      <div class="modal-header">
        <h2 class="modal-title">Add Candidate</h2>
        <button class="btn-close" (click)="closeCandidateModal()">
          <iconify-icon icon="lucide:x"></iconify-icon>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <label class="form-label">Select Election</label>
          <select 
            class="form-select" 
            [(ngModel)]="selectedElectionPubkey"
          >
            <option [value]="null">-- Choose an election --</option>
            <option *ngFor="let election of getActiveElections()" [value]="election.publicKey">
              {{ election.title }}
            </option>
          </select>
        </div>
        <div class="form-group">
          <label class="form-label">Candidate Name</label>
          <input 
            type="text" 
            class="form-input" 
            [(ngModel)]="candidateName" 
            placeholder="Enter candidate name"
            maxlength="32"
          />
          <span class="form-hint">{{ candidateName.length }}/32 characters</span>
        </div>
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" (click)="closeCandidateModal()">Cancel</button>
        <button class="btn btn-primary" (click)="addCandidate()" [disabled]="loading || !candidateName || !selectedElectionPubkey">
          <iconify-icon icon="lucide:user-plus" *ngIf="!loading"></iconify-icon>
          <iconify-icon icon="lucide:loader-2" class="spinning" *ngIf="loading"></iconify-icon>
          <span>{{ loading ? 'Adding...' : 'Add Candidate' }}</span>
        </button>
      </div>
    </div>
  </div>
</div>

// app/voting-nextjs/app/admin/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { useWallet } from '@solana/wallet-adapter-react';
import { WalletMultiButton } from '@solana/wallet-adapter-react-ui';
import { useProgram } from '@/hooks/useProgram';
import { Keypair, SystemProgram, PublicKey } from '@solana/web3.js';
import { ADMIN_SEED } from '@/lib/constants';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Vote, Users, Activity, Database, Plus, RefreshCw } from 'lucide-react';

interface Election {
  publicKey: string;
  title: string;
  isActive: boolean;
  totalVotes: number;
  authority: string;
}

export default function AdminDashboard() {
  const { publicKey } = useWallet();
  const program = useProgram();

  const [loading, setLoading] = useState(false);
  const [elections, setElections] = useState<Election[]>([]);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [electionTitle, setElectionTitle] = useState('');

  // Stats
  const totalElections = elections.length;
  const activeElections = elections.filter(e => e.isActive).length;
  const totalVotes = elections.reduce((sum, e) => sum + e.totalVotes, 0);

  // Fetch elections
  const fetchElections = async () => {
    if (!program) return;

    try {
      setLoading(true);
      const electionAccounts = await program.account.election.all();

      const formattedElections: Election[] = electionAccounts.map((acc: any) => ({
        publicKey: acc.publicKey.toString(),
        title: acc.account.title,
        isActive: acc.account.isActive,
        totalVotes: acc.account.totalVotes.toNumber(),
        authority: acc.account.authority.toString(),
      }));

      setElections(formattedElections);
    } catch (error) {
      console.error('Error fetching elections:', error);
    } finally {
      setLoading(false);
    }
  };

  // Create election
  const handleCreateElection = async () => {
    if (!program || !publicKey) return;
    if (!electionTitle || electionTitle.length > 64) {
      alert('Please enter a valid title (max 64 characters)');
      return;
    }

    try {
      setLoading(true);

      // Generate election keypair
      const electionKeypair = Keypair.generate();

      // Derive admin PDA
      const [adminPda] = PublicKey.findProgramAddressSync(
        [Buffer.from(ADMIN_SEED), publicKey.toBuffer()],
        program.programId
      );

      // Create election transaction
      const tx = await program.methods
        .createElection(electionTitle)
        .accountsStrict({
          authority: publicKey,
          adminAccount: adminPda,
          election: electionKeypair.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([electionKeypair])
        .rpc();

      console.log('Election created:', tx);
      alert(`✅ Election "${electionTitle}" created successfully!`);
      
      setElectionTitle('');
      setShowCreateModal(false);
      
      // Refresh after 2 seconds
      setTimeout(() => fetchElections(), 2000);
    } catch (error: any) {
      console.error('Error creating election:', error);
      
      let errorMsg = 'Failed to create election';
      if (error.message?.includes('Unauthorized')) {
        errorMsg = 'You are not authorized. Make sure you are an admin.';
      } else if (error.message) {
        errorMsg = error.message;
      }
      
      alert(`❌ ${errorMsg}`);
    } finally {
      setLoading(false);
    }
  };

  // Initial fetch
  useEffect(() => {
    if (program && publicKey) {
      fetchElections();
    }
  }, [program, publicKey]);

  if (!publicKey) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-950">
        <Card className="p-8 text-center">
          <h2 className="text-2xl font-bold mb-4">Admin Dashboard</h2>
          <p className="text-gray-400 mb-6">Please connect your wallet to access the admin dashboard</p>
          <WalletMultiButton />
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-950 text-white">
      {/* Sidebar */}
      <aside className="fixed left-0 top-0 bottom-0 w-64 bg-gray-900 border-r border-gray-800">
        <div className="p-6">
          <div className="flex items-center gap-3 mb-8">
            <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-purple-500 to-green-400 flex items-center justify-center">
              <Vote className="w-6 h-6" />
            </div>
            <span className="text-xl font-bold">SolVote Admin</span>
          </div>

          <nav className="space-y-2">
            <a href="#" className="flex items-center gap-3 px-4 py-3 rounded-lg bg-purple-500/10 text-purple-400">
              <Activity className="w-5 h-5" />
              <span>Dashboard</span>
            </a>
          </nav>
        </div>

        <div className="absolute bottom-0 left-0 right-0 p-6 border-t border-gray-800">
          <div className="text-sm text-gray-400">
            <div className="font-medium mb-1">Admin Wallet</div>
            <div className="font-mono text-xs">
              {publicKey.toString().slice(0, 4)}...{publicKey.toString().slice(-4)}
            </div>
          </div>
        </div>
      </aside>

      {/* Main Content */}
      <main className="ml-64 p-8">
        {/* Header */}
        <div className="flex justify-between items-center mb-8">
          <h1 className="text-3xl font-bold">Dashboard Overview</h1>
          <div className="flex gap-3">
            <Button 
              variant="outline" 
              onClick={() => fetchElections()} 
              disabled={loading}
            >
              <RefreshCw className={`w-4 h-4 mr-2 ${loading ? 'animate-spin' : ''}`} />
              Refresh
            </Button>
            <Button onClick={() => setShowCreateModal(true)}>
              <Plus className="w-4 h-4 mr-2" />
              Create Election
            </Button>
          </div>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
          <Card className="p-6">
            <div className="flex justify-between items-start mb-4">
              <span className="text-gray-400 text-sm">Total Elections</span>
              <Database className="w-8 h-8 text-purple-500" />
            </div>
            <div className="text-4xl font-bold mb-2">{totalElections}</div>
            <div className="text-sm text-gray-400">On-chain data</div>
          </Card>

          <Card className="p-6">
            <div className="flex justify-between items-start mb-4">
              <span className="text-gray-400 text-sm">Active Now</span>
              <Activity className="w-8 h-8 text-green-400" />
            </div>
            <div className="text-4xl font-bold mb-2">{activeElections}</div>
            <div className="text-sm text-green-400">Live voting</div>
          </Card>

          <Card className="p-6">
            <div className="flex justify-between items-start mb-4">
              <span className="text-gray-400 text-sm">Total Votes</span>
              <Vote className="w-8 h-8 text-blue-500" />
            </div>
            <div className="text-4xl font-bold mb-2">{totalVotes}</div>
            <div className="text-sm text-gray-400">Votes cast</div>
          </Card>

          <Card className="p-6">
            <div className="flex justify-between items-start mb-4">
              <span className="text-gray-400 text-sm">Voters</span>
              <Users className="w-8 h-8 text-orange-500" />
            </div>
            <div className="text-4xl font-bold mb-2">{totalVotes}</div>
            <div className="text-sm text-gray-400">Registered</div>
          </Card>
        </div>

        {/* Elections List */}
        <div>
          <h2 className="text-2xl font-bold mb-4">Elections</h2>
          {elections.length === 0 ? (
            <Card className="p-12 text-center">
              <Vote className="w-16 h-16 text-gray-600 mx-auto mb-4" />
              <h3 className="text-xl font-bold mb-2">No Elections Yet</h3>
              <p className="text-gray-400 mb-6">Create your first election to get started</p>
              <Button onClick={() => setShowCreateModal(true)}>
                <Plus className="w-4 h-4 mr-2" />
                Create First Election
              </Button>
            </Card>
          ) : (
            <div className="space-y-4">
              {elections.map((election) => (
                <Card key={election.publicKey} className="p-6">
                  <div className="flex justify-between items-center">
                    <div>
                      <h3 className="text-xl font-bold mb-2">{election.title}</h3>
                      <div className="flex gap-4 text-sm text-gray-400">
                        <span className={`px-2 py-1 rounded ${election.isActive ? 'bg-green-500/20 text-green-400' : 'bg-gray-500/20 text-gray-400'}`}>
                          {election.isActive ? 'Active' : 'Closed'}
                        </span>
                        <span>{election.publicKey.slice(0, 8)}...</span>
                        <span>{election.totalVotes} votes</span>
                      </div>
                    </div>
                  </div>
                </Card>
              ))}
            </div>
          )}
        </div>
      </main>

      {/* Create Election Modal */}
      <Dialog open={showCreateModal} onOpenChange={setShowCreateModal}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Create New Election</DialogTitle>
            <DialogDescription>
              Create a new election on the Solana blockchain
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div>
              <Label htmlFor="title">Election Title</Label>
              <Input
                id="title"
                value={electionTitle}
                onChange={(e) => setElectionTitle(e.target.value)}
                placeholder="e.g., Foundation Council Election 2024"
                maxLength={64}
              />
              <p className="text-sm text-gray-400 mt-1">
                {electionTitle.length}/64 characters
              </p>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCreateModal(false)}>
              Cancel
            </Button>
            <Button 
              onClick={handleCreateElection} 
              disabled={loading || !electionTitle}
            >
              {loading ? 'Creating...' : 'Create Election'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
